<template>
    <div class="main-content">
        <ChatTop ref="chatTopRef" :historyLength="history.length" v-model:playAudioID="playAudioID" :recording="recording"
            :showStop="showStop" :localmodel="currentAccount.model === 1000" @sigAudioASRError="sigAudioASRError" />
        <WelcomePage ref="welcomePageRef" v-model:question="question" :recording="recording" :historyLength="history.length"
            v-show="history.length === 0" />
        <div class="chat-history" v-show="history.length > 0">
            <custom-scrollbar :autoHideDelay="2000" :thumbWidth="10" :wrapperStyle="{height: '100%'}" class="history-scrollbar" id="chatHistory" :style="{ width: '100%', height: '100%' ,paddingRight: '20px'}">
                <ChatBubble v-for="(item, index) in history" v-model:playAudioID="playAudioID" :item="item" :showStop="showStop"
                :isLast="history.length === index + 1" :recording="recording" :netState="netState" :hasOutput="hasOutput"
                @handleShowTip="handleShowTip" @retryRequest="retryRequest" />
            </custom-scrollbar>
        </div>
        <div class="chat-bottom">
            <div class="handle-tip">
                <div class="tip-item" v-show="showTopTip">
                    {{ topTipMsg }}
                </div>
                <div class="tip-item" v-show="showCount" v-if="store.loadTranslations['Stop recording after %1 seconds']">
                    <!-- {{ countDown }}S后停止录音 -->

                    {{ store.loadTranslations['Stop recording after %1 seconds'].replace('%1', countDown) }}
                </div>
                <div class="top-stop tip-item" v-show="showStop"  @click="stopRequest">
                    <svgIcon icon="stop" /> {{ store.loadTranslations['Stop'] }}
                </div>
            </div>
            <div class="top">
                <el-tooltip popper-class="uos-tooltip" effect="light" :show-arrow="false" :enterable="false"
                    :show-after="1000" :offset="2" :content="store.loadTranslations['Clear conversation history']">
                    <div class="clear" :class="{ 'disabled': history.length === 0 || disabled || recording }"
                        @click="clearHistory">
                        <SvgIcon icon="clear" />
                    </div>
                </el-tooltip>
                <SwitchModel ref="switchModel" v-model:currentAccount="currentAccount" v-model:accountList="accountList"
                    :disabled="disabled || recording" />
            </div>
            <div class="input-content" :class="{ 'foucs': isFocus }">
                <el-input style="display: none;"></el-input>
                <el-input v-model="question" ref="questionInput" resize="none" :autosize="{ minRows: 4, maxRows: 10 }"
                    type="textarea" :placeholder="store.loadTranslations['Input question']" @focus="isFocus = true"
                    @blur="isFocus = false" @keydown.enter.native="handeleEnter" :disabled="recording" />
                <div class="send-btn">

                    <el-tooltip popper-class="uos-tooltip" effect="light" :show-arrow="false" :enterable="false"
                        :show-after="1000" :offset="2"
                        :content="netState ? !isAudioInput ? store.loadTranslations['Please connect the microphone and try again'] : store.loadTranslations['Voice input'] : store.loadTranslations['Voice input is temporarily unavailable, please check the network!']">
                        <div class="voice-btn btn"
                            :class="{ recording, disabled: !isAudioInput || showStop || !netState, notalking: audioLevel === 0 }"
                            @click="handleRecorder">
                            <SvgIcon icon="voice" />
                        </div>
                    </el-tooltip>
                    <div class="send btn" :class="{ 'disabled': question.trim().length === 0 || disabled }"
                        @click="sendQuestion">
                        <SvgIcon icon="send" />
                    </div>
                </div>
            </div>
            <div class="tip">
                {{ store.loadTranslations[`The content generated by AI is for reference only, please pay attention to the accuracy of the information.`] }}
            </div>
        </div>
    </div>
</template>
<script setup>
import { useGlobalStore } from "@/store/global";
import { Qrequest } from "@/utils";
import _ from "lodash";
import SwitchModel from "./components/SwitchModel.vue";
import WelcomePage from "./components/welcomePage.vue";
import ChatBubble from "./components/ChatBubble.vue";
import ChatTop from "./components/ChatTop.vue";
import CustomScrollbar from 'custom-vue-scrollbar';
import 'custom-vue-scrollbar/dist/style.css';
import { ref } from "vue";

const { chatQWeb, updateActivityColor, updateTheme } = useGlobalStore()
const store = useGlobalStore()
const instance = getCurrentInstance()
console.log(chatQWeb)
const question = ref('')
const isFocus = ref(false)
const showTopTip = ref(false)
// showStop控制 底部的清除icon、发送按钮、语音图标、模型切换、状态切换按钮、<>置灰，播放按钮置灰，设置不置灰，可正常点击
const showStop = ref(false)
const topTipMsg = ref('')
const history = ref([])
const accountList = ref([])
const currentAccount = ref('')
const playAudioID = ref('')
const disabled = computed(() => {
    return showStop.value
})
const isAudioInput = ref(false)
const initChat = async () => {
    const _history = await Qrequest(chatQWeb.getAiChatRecords, false)
    const resAccount = await Qrequest(chatQWeb.queryLLMAccountList)
    const resID = await Qrequest(chatQWeb.currentLLMAccountId)
    isAudioInput.value = await Qrequest(chatQWeb.isAudioInputAvailable)
    hasOutput.value =  await Qrequest(chatQWeb.isAudioOutputAvailable)
    netState.value =  await Qrequest(chatQWeb.isNetworkAvailable)
    history.value = JSON.parse(_history)
    console.log(history.value)
    if (resAccount) {
        const list = JSON.parse(resAccount)
        list.forEach(element => {
            if (element.id === resID) {
                element.active = true
                currentAccount.value = element
            }
        });
        accountList.value = list
    }
    nextTick(() => handelScrol())
}

const talkID = ref('')
const waitSend = ref(false)
const sendQuestion = async () => {
    if (question.value.trim().length === 0 || disabled.value) return
    // 录音中点击发送按钮
    if (recording.value) {
        waitSend.value = true
        sigAudioASRError()
        return
    }
    await Qrequest(chatQWeb.stopPlayTextAudio)
    playAudioID.value = ''
    if (recording.value) sigAudioASRError()
    history.value.push({
        role: 'user',
        content: question.value
    })
    const { id, model, icon, displayname } = currentAccount.value
    const res = await Qrequest(chatQWeb.sendAiRequest, id ? id : '', model ? model : '', 1, question.value, 2)
    history.value.push({
        role: 'assistant',
        anwsers: [
            {
                content: '',
                talkID: res,
                status: 0,
                type: 0,
                llmIcon: icon ? icon : '',
                llmName: displayname ? displayname : ''
            }
        ]
    })
    talkID.value = res
    handelScrol()
    showStop.value = true
    question.value = ''
}
const clearHistory = async () => {
    if (history.value.length === 0 || disabled.value || recording.value) return
    await Qrequest(chatQWeb.clearAiChatRecords)
    await Qrequest(chatQWeb.stopPlayTextAudio)
    playAudioID.value = ''
    history.value = []
    handleShowTip(store.loadTranslations['Chat history cleared'])
    // Qrequest(chatQWeb.showToast,1)
}
const handeleEnter = (event) => {

    if (!event.ctrlKey) {
        // sendQuestion()
    } else {
        event.preventDefault();
        event.stopPropagation();
        document.execCommand('insertText', false, '\n')
    }

}
const handleShowTip = (msg) => {
    showTopTip.value = true
    topTipMsg.value = msg
    setTimeout(() => {
        showTopTip.value = false
    }, 3000)
}

// 接受AI文本信息
const sigAiReplyStream = (type, value, status) => {
    console.log({ type, value, status })
    if (status === 0) {
        _.last(_.last(history.value).anwsers).content = _.last(_.last(history.value).anwsers).content + value
    } else if (status === 200) {
        _.last(_.last(history.value).anwsers).status = status
    } else {
        _.last(_.last(history.value).anwsers).content = value
        _.last(history.value).status = status
        _.last(_.last(history.value).anwsers).status = status
    }
    if (status !== 0) {
        const _question = history.value[history.value.length - 2].content
        const { type, content } = _.last(_.last(history.value).anwsers)
        console.log(talkID.value, _question, content, isRetry.value, status, '', type)
        const { icon, displayname } = currentAccount.value
        Qrequest(chatQWeb.logAiChatRecord, talkID.value, _question, content, isRetry.value, status, '', type, icon, displayname)
        showStop.value = false
        isRetry.value = false
    }
    handelScrol()
}

const handelScrol = () => {
    let chatHistory = document.getElementById('chatHistory')
    if (chatHistory.scrollHeight > chatHistory.clientHeight) {
        setTimeout(() => {
            chatHistory.scrollTop = chatHistory.scrollHeight;
        }, 0);
    }
}

const stopRequest = async () => {
    await Qrequest(chatQWeb.cancelAiRequest, talkID.value)
    const _question = history.value[history.value.length - 2].content
    const { type, content } = _.last(_.last(history.value).anwsers)
    const { icon, displayname } = currentAccount.value
    Qrequest(chatQWeb.logAiChatRecord, talkID.value, _question, content, isRetry.value, 0, '', type, icon ? icon : '', displayname ? displayname : '')
    showStop.value = false
    isRetry.value = false
}

// 重新生成
const isRetry = ref(false)
const retryRequest = async () => {
    const _question = history.value[history.value.length - 2].content
    await Qrequest(chatQWeb.stopPlayTextAudio)
    playAudioID.value = ''
    if (recording.value) sigAudioASRError()
    const { id, model, icon, displayname } = currentAccount.value
    const res = await Qrequest(chatQWeb.sendAiRequest, id ? id : '', model ? model : '', 1, _question, 2)
    _.last(history.value).anwsers.push({
        content: '',
        status: '',
        talkID: res,
        type: 0,
        llmIcon: icon ? icon : '',
        llmName: displayname ? displayname : ''
    })
    talkID.value = res
    isRetry.value = true
    showStop.value = true
    // question.value = ''
}

const recording = ref(false)
const startQus = ref('')
const endQus = ref('')

const handleRecorder = async () => {
    console.log(recording.value)
    if (!isAudioInput.value || showStop.value || !netState.value) return
    if (recording.value) return sigAudioASRError()
    if (!recording.value) {
        isAudioInput.value = await Qrequest(chatQWeb.isAudioInputAvailable)
        await Qrequest(chatQWeb.stopPlayTextAudio)
        if (isAudioInput.value) {
            await Qrequest(chatQWeb.startRecorder)
            const insert = questionInput.value.textarea.selectionStart;
            startQus.value = questionInput.value.textarea.value.substr(0, insert)
            endQus.value = questionInput.value.textarea.value.substr(insert)
            recording.value = true
            playAudioID.value = ''
        }
    }
}

// AI模型列表更新
const llmAccountLstChanged = (id, list) => instance.proxy.$Bus.emit("llmAccountLstChanged", { id, list })


const questionInput = ref()
const sigAudioASRStream = (res, isEnd) => {
    question.value = startQus.value + res + endQus.value
    // console.log('sigAudioASRStream', res, isEnd)
    if (isEnd) {
        if (waitSend.value) {
            waitSend.value = false
            sendQuestion()
        }
        sigAudioASRError()
        questionInput.value.focus()
    }
}

const countDown = ref(0)
const showCount = ref(false)
const sigAudioCountDown = (res) => {
    countDown.value = res
    if(res>0) showCount.value = true
    if(res===0) {
        setTimeout(()=>showCount.value = false,1000)
    }
}

const sigAudioASRError = () => {
    recording.value = false
    countDown.value = 0
    audioLevel.value = 0
    showCount.value = false
    Qrequest(chatQWeb.stopRecorder)
}
// 语音播放结束
const sigPlayTTSFinished = (res) => {
    console.log('sigPlayTTSFinished', res)
    if (playAudioID.value === res) playAudioID.value = ''
}

const sigPlayTTSError = (res) => playAudioID.value = ''

// const sigAudioRecShortcutPressed = () => handleRecorder()
const sigAudioInputDevChange = (res) => {
    isAudioInput.value = res
    if (!res) recording.value = false
}
const hasOutput = ref(true)
const sigAudioOutputDevChanged = (res) => { 
    if (!res) playAudioID.value = ''
    hasOutput.value = res
}

const sigChatConversationType = (id, type) => {
    // console.log(id, action)
    _.last(_.last(history.value).anwsers).type = type
}
// 接受AI图片信息
const sigText2PicFinish = (id, paths) => {
    _.last(_.last(history.value).anwsers).content = JSON.stringify(paths)
    const _question = history.value[history.value.length - 2].content
    const _type = _.last(_.last(history.value).anwsers).type
    console.log(talkID.value, _question, paths, isRetry.value, 0, '', _type)
    const { icon, displayname } = currentAccount.value

    Qrequest(chatQWeb.logAiChatRecord, talkID.value, _question, JSON.stringify(paths), isRetry.value, 0, '', _type, icon ? icon : '', displayname ? displayname : '')
    handelScrol()
    showStop.value = false
    isRetry.value = false
}
const welcomePageRef = ref()
const sigWebchat2BeHiden = () => {
    Qrequest(chatQWeb.stopPlayTextAudio)
    playAudioID.value = ''
    welcomePageRef.value.getAiFAQ()
    sigAudioASRError()
}
// 监听AI进程被杀
// const connectStateChanged = (status) => instance.proxy.$Bus.emit("connectStateChanged", status)
// 活动色改变
const sigActiveColorChanged = (res) => updateActivityColor(res)
const audioLevel = ref(0)
const sigAudioSampleLevel = (res) => audioLevel.value = res
const sigThemeChanged = (res) => updateTheme(res)
const netState = ref(true)
const sigNetStateChanged = (res) => netState.value = res
//ctrl+super+c跳转到数字人
const chatTopRef = ref()
const sigDigitalModeActive = () => {
    if (currentAccount.value.model === 1000|| showStop.value|| recording.value) return;
    chatTopRef.value.handelModel();
};
const handleActive = (res) =>{
    let maskDom = document.querySelector('#drop-mask');
    if (!maskDom) {
        maskDom = document.createElement("div");
        maskDom.id = "drop-mask"
        document.body.appendChild(maskDom);
    }
    maskDom.style.height = '100vh'
    maskDom.style.width = '100vw'
    maskDom.style.display = res ? 'flex' : 'none'
}
const switchModel = ref()
const sigWebchatActiveChanged = (res)=> {
    
    if(!res) {
        switchModel.value.showSwitchMenu = false
        chatTopRef.value.showSeting = false
    }
    // handleActive(res)
}
const sigWebchatModalityChanged = (res) => handleActive(res)
const responseAIFunObj = {
    sigAiReplyStream,
    llmAccountLstChanged,
    sigActiveColorChanged,
    sigAudioASRStream,
    sigAudioASRError,
    sigAudioCountDown,
    sigPlayTTSFinished,
    sigPlayTTSError,
    // sigAudioRecShortcutPressed,
    sigAudioInputDevChange,
    sigAudioOutputDevChanged,
    sigChatConversationType,
    sigText2PicFinish,
    sigThemeChanged,
    sigWebchat2BeHiden,
    sigAudioSampleLevel,
    sigNetStateChanged,
    sigDigitalModeActive,
    sigWebchatActiveChanged,
    sigWebchatModalityChanged
    // connectStateChanged
}
function handleKeyDown(event) {
    if (event.key === "Enter") {
        event.stopPropagation()
        event.preventDefault()
        console.log('chat')
        sendQuestion()
    }
}
onMounted(async () => {
    for (const key in responseAIFunObj) {
        if (Object.hasOwnProperty.call(responseAIFunObj, key)) {
            chatQWeb[key].connect(responseAIFunObj[key]);
        }
    }
    document.addEventListener("keydown", handleKeyDown);
    initChat()

    useGlobalStore().loadTranslations = await Qrequest(chatQWeb.loadTranslations)
    console.log(useGlobalStore().loadTranslations)
})
onBeforeUnmount(() => {
    for (const key in responseAIFunObj) {
        if (Object.hasOwnProperty.call(responseAIFunObj, key)) {
            chatQWeb[key].disconnect(responseAIFunObj[key]);
        }
    }
    document.removeEventListener("keydown", handleKeyDown);
})
</script>

<style lang="scss" scoped>
.main-content {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
    overflow: hidden;

    .chat-history {
        padding: 15px 0px 15px 20px;
        flex: 1 1 0;
        margin-right: 3px;
        margin-top: -25px;
        overflow: hidden;
        .history-scrollbar{
            overflow-y: overlay;
            overflow-x: hidden;
            height: 100%;
        }
    }

    .chat-bottom {
        padding: 0 10px;
        margin-top: auto;
        margin-bottom: 10px;
        position: relative;

        .handle-tip {
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            top: -50px;

            .tip-item {
                color: var(--uosai-color-tip);
                font-size: 13px;
                font-weight: 500;
                font-style: normal;
                padding: 6px 15px;
                border-radius: 18px;
                border: 1px solid rgba(0, 0, 0, 0.05);
                box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.05);
                background-color: var(--uosai-color-tip-bg);
                margin: 0 auto;
                text-align: center;
                margin-bottom: 10px;
                width: fit-content;
                user-select: none;
            }

            .top-stop {
                color: var(--activityColor);
                background-color: var(--uosai-color-stop-bg);
                border-radius: 8px;

                cursor: pointer;
                box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.05);
                border: none;
                svg {
                    width: 15px;
                    height: 15px;
                    margin-bottom: -3px;
                }
            }
        }



        .top {
            margin-bottom: 10px;
            padding-left: 5px;
            display: flex;
            align-items: center;

            .clear {
                width: 36px;
                height: 36px;
                background-color: var(--uosai-color-shortcut-bg);
                border-radius: 8px;
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
                margin-right: auto;

                &:not(.disabled):hover {
                    background-color: var(--uosai-color-shortcut-hover);

                    svg {
                        fill: var(--uosai-color-clear-hover);
                    }
                }

                &:not(.disabled):active {
                    background-color: var(--uosai-color-shortcut-active);

                    svg {
                        fill: var(--activityColor);
                    }
                }

                svg {
                    height: 20px;
                    width: 20px;
                    fill: var(--uosai-color-clear);
                }
            }

        }

        .input-content {
            min-height: 120px;
            height: auto;
            border-radius: 8px;
            opacity: 1;
            background-color: var(--uosai-color-inputcontent-bg);
            margin-bottom: 7px;
            padding-bottom: 8px;
            border: 2px solid rgba(0, 0, 0, 0);


            &.foucs {
                border: 2px solid var(--activityColor);
            }

            :deep(.el-textarea) {
                padding-top: 10px;
                .el-textarea__inner {
                    box-shadow: none;
                    background: none;
                    color: var(--uosai-color-inputcontent);
                    font-size: 13px;

                    &::placeholder {
                        color: var(--uosai-color-inputcontent-placeholder);
                        font-size: 13px;
                        font-weight: 500;
                        user-select: none;
                    }

                    &::-webkit-scrollbar {
                        background: none;
                        width: 6px;
                        height: 6px;
                        &:hover {
                            width: 8px;
                            height: 8px;
                        }
                    }

                    &::-webkit-scrollbar-thumb {
                        border-radius: 4px;
                        background: var(--uosai-color-scroll-bg);
                        border: 1px solid var(--uosai-color-border);
                        // box-shadow: 0px 0px 10px 0px var(--uosai-color-border);
                    }

                    &:focus {
                        outline: 0;
                        box-shadow: none;
                    }
                }
            }

            .send-btn {
                height: 30px;
                display: flex;
                justify-content: flex-end;
                margin-top: 6px;

                .btn {
                    // box-shadow: 0px 4px 6px rgba(44, 167, 248, 0.4);
                    background-color: var(--activityColor);
                    width: 30px;
                    height: 30px;
                    border-radius: 50%;
                    margin-right: 8px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    cursor: pointer;

                    &.send {
                        box-shadow: 0 4px 6px 0 var(--boxShadow);

                        svg {
                            fill: #fff;
                        }
                    }

                    svg {
                        width: 12px;
                        height: 12px;
                    }

                    &.disabled {
                        opacity: 0.4;
                        cursor: not-allowed;
                    }

                    &.send:not(.disabled):hover {
                        filter: brightness(1.2);
                    }

                    &.send:not(.disabled):active {
                        filter: brightness(1.1);

                        svg {
                            fill: rgba(255, 255, 255, 0.6);
                        }
                    }

                }

                .voice-btn {
                    background-color: var(--uosai-color-voicebtn-bg);
                    margin-right: 15px;

                    &:not(.disabled):hover {
                        background-color: var(--uosai-color-voicebtn-bg-hover);
                    }

                    &:not(.disabled):active {
                        background-color: var(--uosai-color-voicebtn-bg-active);

                        svg {
                            opacity: 0.6;
                        }
                    }

                    svg {
                        width: 12px;
                        height: 17px;
                        fill: var(--activityColor);
                    }

                    &.recording::before {
                        content: '';
                        position: absolute;
                        opacity: 0.4;
                        border-radius: 50%;
                    }

                    &.recording::after {
                        content: '';
                        position: absolute;
                        opacity: 0.1;
                        border-radius: 50%;

                    }

                    @keyframes Wave1 {
                        0% {
                            border: 2px solid var(--activityColor);
                            width: 30px;
                            height: 30px;
                        }

                        100% {
                            border: 6px solid var(--activityColor);
                            width: 30px;
                            height: 30px;
                        }
                    }

                    @keyframes Wave2 {
                        0% {
                            border: 3px solid var(--activityColor);
                            width: 34px;
                            height: 34px;
                        }

                        100% {
                            border: 5px solid var(--activityColor);
                            width: 40px;
                            height: 40px;

                        }
                    }

                    &:not(.notalking).recording::before {
                        animation: Wave1 0.4s ease-in-out infinite;
                        animation-direction: alternate-reverse;

                    }

                    &:not(.notalking).recording::after {
                        animation: Wave2 0.4s ease-in-out infinite;
                        animation-direction: alternate-reverse;
                    }

                    @keyframes notalking1 {
                        0% {
                            border: 1px solid var(--activityColor);
                            width: 30px;
                            height: 30px;
                        }

                        100% {
                            border: 3px solid var(--activityColor);
                            width: 30px;
                            height: 30px;
                        }
                    }

                    @keyframes notalking2 {
                        0% {
                            border: 3px solid var(--activityColor);
                            width: 32px;
                            height: 32px;
                        }

                        100% {
                            border: 4px solid var(--activityColor);
                            width: 36px;
                            height: 36px;

                        }
                    }

                    &.notalking::before {
                        animation: notalking1 0.8s ease-in-out infinite;
                        animation-direction: alternate-reverse;

                    }

                    &.notalking::after {
                        animation: notalking2 0.8s ease-in-out infinite;
                        animation-direction: alternate-reverse;

                    }
                }
            }
        }

        .tip {
            color: var(--uosai-color-inputcontent-placeholder);
            font-size: 12px;
            font-weight: 500;
            font-style: normal;
            text-align: left;
            padding-left: 10px;
            user-select: none;
        }
    }
}
.dark {
    .top-stop{
        box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.15) !important;
    }
}
</style>
